void _puts_recursion(char *s);
int _putchar(char s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int find_sqrt(int a, int b);
int is_prime_number(int n);
int find_prime(int a, int n);
int is_palindrome(char *s);
int string_length(char *s);
int compare_letters(char *s, int start, int end);
int wildcmp(char *s1, char *s2);
